// Scenario runbook template
:scenario-id: DC1
:category: Single DC failure
:name: Full datacenter failure
:description: Full datacenter (e.g. disaster, power outage, DC switch failure) outage

== {scenario-id}: {name} ({category})

=== Description 

{description}

=== Failover steps to degraded state

. Switch over from hierarchical quorum to normal quorum.
+
====
include::../../../steps/switch_to_normal_quorum.adoc[]
====
. Ensure there are no offline partitions, i.e. partitions whose leader is not available.
+
====
include::../../../steps/ensure_no_offline_partitions.adoc[]
====
. If there are offline partitions and availability of data requires prioritization over other factors, then trigger unclean election with care.
+
====
include::../../../steps/unclean_leader_election.adoc[]
====
. If your producers are blocked because the topic partition(s) you are trying to produce to is not sufficiently replicated to match the configured topics' `min.insync.replicas`, you can unblock it by altering the topic(s) settings.
+
====
include::../../../steps/update_mir_in_bulk.adoc[]
====


=== Recovery steps to normal state
. Resolve datacenter outage.
. Perform failback for Zookeeper nodes that were switched from Zookeeper hierarchical quorum to normal quorum.
+
====
include::../../../steps/switch_to_hierarchical_quorum.adoc[]
====
. Check if your Zookeeper's hierarhical quorum is online.
+
====
include::../../../steps/ensure_quorum.adoc[]
====
NOTE: Once Zookeeper hierarchical quorum is restored, your Kafka brokers will rejoin and resync.
. Ensure there are no under replicated partitions.
+
====
include::../../../steps/ensure_no_urp.adoc[]
====
+
NOTE: It may take a while before all replicas are caught up.
. Restore `min.insync.replicas` back to your desired value, e.g. MIR=4 if you require guarantee that every event produced to both DCs.
+
====
include::../../../steps/update_mir_in_bulk.adoc[]
====


