---
all:
  vars:
    ansible_connection: ssh

    #FIXME: TO UPDATE WITH YOUR SSH USER FOR YOUR HOSTS
    ansible_user: ec2-user

    ansible_become: true

    #FIXME: TO REMOVE IF YOU ARE USING PASSWORDLESS SSH TO HOSTS 
    ansible_ssh_private_key_file: /home/ec2-user/ivantang-aws-sg.pem

    jolokia_enabled: true
    jmxexporter_enabled: true
    
    kafka_broker_custom_listeners:
      client_listener:
        name: CLIENT
        port: 9093


##################################################
#  3+3 Zookeeper nodes with hierarchical quorum  #
##################################################

zookeeper:
  vars:
    zookeeper_custom_properties:
      group.1: '1:2:3'
      group.2: '4:5:6'

      #FIXME: REPLACE WITH YOUR ZK HOSTNAMES
      server.1: ip-10-0-0-196.ap-southeast-1.compute.internal:2888:3888
      server.2: ip-10-0-0-238.ap-southeast-1.compute.internal:2888:3888
      server.3: ip-10-0-0-233.ap-southeast-1.compute.internal:2888:3888
      server.4: ip-10-0-0-35.ap-southeast-1.compute.internal:2888:3888
      server.5: ip-10-0-0-17.ap-southeast-1.compute.internal:2888:3888
      server.6: ip-10-0-0-15.ap-southeast-1.compute.internal:2888:3888
      weight.1: 1
      weight.2: 1
      weight.3: 1
      weight.4: 1
      weight.5: 1
      weight.6: 1
      4lw.commands.whitelist: stat,ruok,conf,isro,mntr,wchc
      clientPort: 2181
  hosts:
    #FIXME: REPLACE WITH YOUR ZK HOSTNAMES
    ip-10-0-0-196.ap-southeast-1.compute.internal:
    ip-10-0-0-238.ap-southeast-1.compute.internal:
    ip-10-0-0-233.ap-southeast-1.compute.internal:
    ip-10-0-0-35.ap-southeast-1.compute.internal:
    ip-10-0-0-17.ap-southeast-1.compute.internal:
    ip-10-0-0-15.ap-southeast-1.compute.internal:
    

#################################
#  3+3 Stretched Kafka cluster  #
#################################

kafka_broker:
  vars:
    #NOTE: Leaving an example on how to include environment overrides
    #kafka_broker_service_environment_overrides:
    #      KAFKA_HEAP_OPTS: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname={{inventory_hostname}} -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.rmi.port=9101 -Dcom.sun.management.jmxremote.port=9101 -Dcom.sun.management.jmxremote.port=9101"
    kafka_broker_custom_properties:

      #FIXME: UPDATE WITH YOUR REQUIRED RETENTION PERIOD. 
      #NOTE: Topic can still be configured with a different retention period.
      log.retention.hours: 12 


      #FIXME: INSERT YOUR LICENSE
      confluent.license: xxx 
      
      # Ensure MIR >= total_brokers/2 + 1
      min.insync.replicas: 4

      # Ensure RF = total_brokers
      default.replication.factor: 6

      # Ensure rack awareness on topic creation
      replica.selector.class: org.apache.kafka.common.replica.RackAwareReplicaSelector

      # Enable self balancing cluster (SBC) feature
      confluent.balancer.enable: true

      # Note the following is only enforced during topic creation
      offsets.topic.replication.factor: 6
      transaction.state.log.replication.factor: 6
      confluent.metrics.reporter.topic.replicas: 6
      confluent.balancer.topic.replication.factor: 6
      confluent.license.topic.replication.factor: 6
      confluent.metadata.topic.replication.factor: 6
      confluent.security.event.logger.exporter.kafka.topic.replicas: 6
      confluent.tier.metadata.replication: 6 # FIXME: Required if you intend to use tier storage in the future.

      #TODO: INSERT OTHER ADDITIONAL BROKER PROPERTIES IF REQUIRED.
      

  hosts:
    #FIXME: REPLACE WITH BROKER 1 HOSTNAME
    ip-10-0-0-218.ap-southeast-1.compute.internal:
      kafka_broker_custom_properties:
        broker.rack: 'DC1'
        broker.id: 1
      kafka_broker_custom_listeners:
        client_listener:
            #FIXME: INSERT BROKER 1 PUBLICLY ACCESSIBLE HOSTNAME, IF REQUIRED
            hostname:

    #FIXME: REPLACE WITH BROKER 2 HOSTNAME
    ip-10-0-0-199.ap-southeast-1.compute.internal: 
      kafka_broker_custom_properties:
        broker.rack: 'DC1'
        broker.id: 2
      kafka_broker_custom_listeners:
        client_listener:
            #FIXME: INSERT BROKER 2 PUBLICLY ACCESSIBLE HOSTNAME, IF REQUIRED
            hostname:

    #FIXME: REPLACE WITH BROKER 3 HOSTNAME
    ip-10-0-0-221.ap-southeast-1.compute.internal:
      kafka_broker_custom_properties:
        broker.rack: 'DC1'
        broker.id: 3
      kafka_broker_custom_listeners:
        client_listener:
            #FIXME: INSERT BROKER 3 PUBLICLY ACCESSIBLE HOSTNAME, IF REQUIRED
            hostname:

    #FIXME: REPLACE WITH BROKER 4 HOSTNAME
    ip-10-0-0-34.ap-southeast-1.compute.internal:
      kafka_broker_custom_properties:
        broker.rack: 'DC2'
        broker.id: 4
      kafka_broker_custom_listeners:
        client_listener:
            #FIXME: INSERT BROKER 4 PUBLICLY ACCESSIBLE HOSTNAME, IF REQUIRED
            hostname:

    #FIXME: REPLACE WITH BROKER 5 HOSTNAME
    ip-10-0-0-55.ap-southeast-1.compute.internal:
      kafka_broker_custom_properties:
        broker.rack: 'DC2'
        broker.id: 5
      kafka_broker_custom_listeners:
        client_listener:
            #FIXME: INSERT BROKER 5 PUBLICLY ACCESSIBLE HOSTNAME, IF REQUIRED
            hostname:

    #FIXME: REPLACE WITH BROKER 6 HOSTNAME
    ip-10-0-0-15.ap-southeast-1.compute.internal:
      kafka_broker_custom_properties:
        broker.rack: 'DC2'
        broker.id: 6
      kafka_broker_custom_listeners:
        client_listener:
            #FIXME: INSERT BROKER 6 PUBLICLY ACCESSIBLE HOSTNAME, IF REQUIRED
            hostname:

control_center:
  vars:
    control_center_custom_properties:
      #FIXME: INSERT YOUR LICENSE HERE
      confluent.license: 

  hosts:
    ip-10-0-0-215.ap-southeast-1.compute.internal:
